# Trigger rebuild
# Basic site configuration
baseURL = 'https://weijie-zhu.github.io/'
languageCode = 'en-us'
title = "Ju"

# Navigation menu items
[menu]
  [[menu.main]]
    name = "Home"      # Display name
    url = "/"          # URL to link to
    weight = 1         # Order in menu (lowest number appears first)
  
  [[menu.main]]
    name = "View"
    url = "/view/"    # Changed from /photos/ to /view/
    weight = 2
  
  [[menu.main]]
    name = "Gallery"
    url = "/gallery/"
    weight = 3
  
  [[menu.main]]
    name = "Project"
    url = "/project/"
    weight = 4

  [[menu.main]]
    name = "Blog"
    url = "/blog/"
    weight = 5
  
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 6

[params.social]
  # Icons will be displayed in the order listed here
  [[params.social.list]]
    icon = "facebook"
    url = "https://facebook.com/teruzz77"
  [[params.social.list]]
    icon = "instagram"
    url = "https://instagram.com/teruzz77"
  [[params.social.list]]
    icon = "youtube"
    url = "https://www.youtube.com/@JUJU-lh1ov"
  [[params.social.list]]
    icon = "bilibili"
    url = "https://space.bilibili.com/142718963/upload/video"
